### ISSUE TITLE
非常棒的工作。有个问题请教一下。

### ISSUE THREAD

**Issue by yujack333** [PKU-YuanGroup/Envision3D#6]
关于Evaluation Metrics如何计算的。请问PSNR、SSIM等的预测图和GT图是如何获取的呢？预测图是从3d模型中特定角度渲染的吗？可否共享一下这部分的代码？万分感激。

**Comment by Pang-Yatian** [comment]
Hi,
For evaluation metrics, you can refer to syncdreamer. To calculate PSNR,SSIM, we inference our model to get generated images and also render the GT images. They are from the same camera poses. For rendering code you can refer to zero123.
